name: Release Drafter for develop branch

on:
  push:
    # branches to consider in the event; optional, defaults to all
    branches:
      - develop
env:
  VERSION_PREFIX: stg-

permissions:
  contents: read

jobs:
  update_release_draft:
    permissions:
      # write permission is required to create a github release
      contents: write
      # write permission is required for autolabeler
      # otherwise, read permission is required at least
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Generate build-number
        id: buildnum
        run: |
          RELEASE_TAGS=$(gh release --repo ${{github.repository}} list --exclude-drafts --exclude-pre-releases | tail -n +1  | grep '^${{env.VERSION_PREFIX}}' | wc -l)

          MAJOR_VERSION=0
          PATCH_VERSION=$(expr ${RELEASE_TAGS} + 1)

          VERSION="${{env.VERSION_PREFIX}}${PATCH_VERSION}"

          echo "version=${VERSION}" >> $GITHUB_OUTPUT
          echo "Version set to ${VERSION}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: release-drafter/release-drafter@v5
        with:
          tag: ${{ steps.buildnum.outputs.version }}
          name: ${{ steps.buildnum.outputs.version }}
          version: ${{ steps.buildnum.outputs.version }}
          config-name: "stg-release-drafter.yml"
          disable-autolabeler: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}